### ISSUE TITLE
Times do not appear

### ISSUE THREAD

**Issue by dogchester** [ClassicSpeed/backloggd-hltb#1]
I've tried this extension on Firefox and Chrome, but I can not get the times to show up.

![1](https://github.com/ClassicSpeed/backloggd-hltb/assets/51802458/5202cf8c-3e9d-4ffb-a15f-38c5af7aef34)

![2](https://github.com/ClassicSpeed/backloggd-hltb/assets/51802458/f1416dcc-df08-450b-b1ab-fa6f344bfe6b)

**Comment by ClassicSpeed** [comment]
I think it's a problem with the permissions. 
By default you can grant temporal permissions in Firefox by left-clicking the add-on icon on the top right. 

Try giving the extension the for the website:
1. Go to backlogg.com
2. Click on the addon icon with the right click.
3. Select "Always allow on backloggd.com"

![image](https://github.com/ClassicSpeed/backloggd-hltb/assets/10333814/81a3f60f-f24a-4fcf-9598-cb16e6bba36c)

There is something similar in the extension manager of chrome, you can enter in the details of the extension and check in the "Site access" section if it's allowed for the backloggd page.

**Comment by ClassicSpeed** [comment]
Not getting a comment in two months so I'm closing the issue. Try the new v1.0 update and if there is any problem, open a new issue.
