### ISSUE TITLE
Overlapping with "notes" in list

### ISSUE THREAD

**Issue by outerwinnie** [ClassicSpeed/backloggd-hltb#2]
![firefox_2024-07-02-23-09-34](https://github.com/ClassicSpeed/backloggd-hltb/assets/6392320/1472f1ca-54a7-493e-b1da-44b2ed323657)

Would it be possible to change the position? Maybe choose in what corner you want it?

Amazing add-on btw

**Comment by ClassicSpeed** [comment]
Nice suggestion! I added the option in the extension icon right-click menu to chose the corner you want, right below the kind of  time to show option. I also fixed some problems with the menu not working right all the time.

The change is already published on version 1.0 in both Chrome and Firefox!

![image](https://github.com/ClassicSpeed/backloggd-hltb/assets/10333814/50bf37f4-a7b4-45c1-b674-8696b1d04fc6)
