### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by outerwinnie** [ClassicSpeed/backloggd-hltb#3]
It doesn't load data anymore for some reason:

![imagen](https://github.com/user-attachments/assets/99566956-c0da-41d6-a89f-f3519f446f45)

**Comment by ClassicSpeed** [comment]
I'm sorry to say but the HLTB API is down (or restricted maybe? it says unauthorized now).  I'll keep an eye on the issue to see if it fixes itself, in the meantime I'll try to search for alternatives.

**Comment by outerwinnie** [comment]
It may be a problem with the plugin making to many requests, and thus been limited now. I don't know if it's possible but maybe it would be good if you could cache the data and not requesting them every time you open the web.

**Comment by ClassicSpeed** [comment]
The plugin already caches your request, that's why it shows the time really fast if you reload (well, when it was working at least). The problem is the HLTB API not longer working, and if I'm not mistaken, every HLTB plugin (like the one for steam deck for example) should be broken too.
I hope it's just a temporal thing, I'm open to use another page instead of HLTB if that's necessary, I'll update the issue if I find any solution.

**Comment by outerwinnie** [comment]
> The plugin already caches your request, that's why it shows the time really fast if you reload (well, when it was working at least). The problem is the HLTB API not longer working, and if I'm not mistaken, every HLTB plugin (like the one for steam deck for example) should be broken too. I hope it's just a temporal thing, I'm open to use another page instead of HLTB if that's necessary, I'll update the issue if I find any solution.

I do have a Steam Deck, and the HLTB plugin still works there. Thanks for your amazing plugin!

**Comment by ClassicSpeed** [comment]
Oh okay then, I'll try to see what the plugin does, since it's open source too, thanks for the info :D

**Comment by outerwinnie** [comment]
The Deck plugin doesn't work since a few days ago, but someone on their discord says this:
![Screenshot_2024-07-28-23-01-32-633_com discord](https://github.com/user-attachments/assets/1d435b99-b1cb-4457-a192-7527cdfdeecf)

I think it may be helpful!

**Comment by ClassicSpeed** [comment]
I'll try that right now, thanks for the info!

**Comment by ClassicSpeed** [comment]
Never mind that, the HTLB proxy I was using is fixed, the plugin is working again!
