### ISSUE TITLE
It stopped working

### ISSUE THREAD

**Issue by Bakkestaffen** [ClassicSpeed/backloggd-hltb#4]
It constantly flip-flopped between working and not when I downloaded it like a week ago on Chrome. Now it never works. I checked, and it is indeed enabled.

**Comment by ClassicSpeed** [comment]
Sorry, the HLTB API is giving some problems right now, I'm currently trying to fix it.

**Comment by ClassicSpeed** [comment]
The HTLB proxy I was using is fixed, the plugin is working again!

**Comment by Bakkestaffen** [comment]
Sorry, but it still ain't working. I revomed and redownloaded it, and it still is not working.

**Comment by ClassicSpeed** [comment]
Oh sorry, it's a separate problem then, I re-opened the issue. 
To help you I need more information. Are the time badges showing with a "-" instead of the time or they aren't showing up at all?
Also what version of the extension and chrome and you using?

**Comment by Bakkestaffen** [comment]
They're not showing up at all. The version I'm using is the one you have linked: https://chromewebstore.google.com/detail/hltb-extension-for-backlo/hlbfmkkpoejdgflgpmcpjohjhablmcfj

As for which version of Chrome I'm using...there are more than one? Because if it is, then I'm definitely using the main version.

**Comment by ClassicSpeed** [comment]
Sorry I wasn't clear enough, i meant the version number, in chrome you can press the 3 dots > Help >  About Google Chrome
![image](https://github.com/user-attachments/assets/170a75c7-6ecf-4499-8608-44e3aac81f98)
But more importantly, to see your extension version for to chrome://extensions/ and look for the extension information. you can press on "Details" and see information about the extension like version number and permissions (I think you can just paste this without quotes on the chrome bar and it will get you there: "chrome://extensions/?id=hlbfmkkpoejdgflgpmcpjohjhablmcfj")
A screenshot of the whole setting page would help a lot, like this:

![image](https://github.com/user-attachments/assets/c6bbb2f8-6d6f-4400-a568-62b2507d9d06)
Probably the extension is missing permissions?

**Comment by Bakkestaffen** [comment]
Can you read Norwegian? Anyways, I updated Chrome, it still isn't working.

![Skjermbilde 2024-07-29 210805](https://github.com/user-attachments/assets/53c1fb3f-fae5-4f8f-b78f-230fd57fd6a8)
![Skjermbilde 2024-07-29 210808](https://github.com/user-attachments/assets/528d0434-4dc3-45fd-bfbb-55e4c9d61885)

**Comment by ClassicSpeed** [comment]
Everything looks okay setting wise. I'm not sure I can help you that much now, but can you try to open the developer console (F12 while on chrome) and show me if there is any errors?
It would look something like this:

![image](https://github.com/user-attachments/assets/307c7b12-70e7-4019-9aca-3fdd427b900a)

Also, I'm not suggesting that you move to FireFox, but if you are able to download it and try [the add-on](https://addons.mozilla.org/en-US/firefox/addon/hltb-extension-for-backloggd/) (just to see if it's a connection problem or a chrome problem) that could help

**Comment by Bakkestaffen** [comment]
Did it for FF too. Nothing there either. App says it cannot run on this site:
![Uploading Skjermbilde 2024-07-29 234508.png…]()

**Comment by Bakkestaffen** [comment]
Didn't work there either: 
![Uploading Skjermbilde 2024-07-29 234508.png…]()

**Comment by Bakkestaffen** [comment]
![Skjermbilde 2024-07-29 234508](https://github.com/user-attachments/assets/49915f0f-3d32-4418-865b-0c177d81be91)

**Comment by Bakkestaffen** [comment]
Hmm, there are some errors on Chrome, yes. At least two of them relate to this site. Maybe that's the problem, but I don't understand how to fix them. I click on them and see no help in regards to that

![Skjermbilde 2024-07-30 004714](https://github.com/user-attachments/assets/52b8d2f7-9cee-4634-b688-9dbb74652bcc)

**Comment by ClassicSpeed** [comment]
I'm not sure but I think some other extension is causing problems.
Can you disable every other extension and see if the extension works? Also if it does, try enabling the other extensions one by one to see if you find the problem.

**Comment by Bakkestaffen** [comment]
Just did all of that and even deleted and redownloaded this afterwards. Still, nothing.

**Comment by ClassicSpeed** [comment]
I'm sorry Bakkestaffen, I don't think I can help you. I tried changing the chrome's language to Norwegian to see if it was a language issue but it just works for me. I genuinely don't know how to fix the problem, you can try the FireFox version but that's hardly a fix. Again I'm really sorry

**Comment by vazzot** [comment]
Hi! I'm also having a similar issue. I'm using the brave browser, and it shows that the extension is there, but for some reason all of the times are justs lines (-) and it doesn't seem to go away. Any possible way to fix this? Thank you.

![lines](https://github.com/user-attachments/assets/9270abeb-7070-4eba-9099-2a769894622f)

**Comment by Bakkestaffen** [comment]
> Hi! I'm also having a similar issue. I'm using the brave browser, and it shows that the extension is there, but for some reason all of the times are justs lines (-) and it doesn't seem to go away. Any possible way to fix this? Thank you.
> 
> ![lines](https://private-user-images.githubusercontent.com/177476589/354918533-9270abeb-7070-4eba-9099-2a769894622f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4MDg0OTgsIm5iZiI6MTcyMjgwODE5OCwicGF0aCI6Ii8xNzc0NzY1ODkvMzU0OTE4NTMzLTkyNzBhYmViLTcwNzAtNGViYS05MDk5LTJhNzY5ODk0NjIyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNFQyMTQ5NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDU2OWY0ZmQyNDZmM2RlZGZiZmViNWQzMzNiYTEyNDMxYjVkMTYwZmU4ZjVmMDE2NDJmNTQyNzM4M2U5ZWViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6um0GvpRY9UwU7mnT7H1L5TDdRKAtPBd8dFDzVtm0Nc)

Yeah, that shows up now at me too. Nothing at all showed up there when I was posting all of the above, now, I get that exact same error.

**Comment by ClassicSpeed** [comment]
I think is working right now? The current problem is he HLTB API that's causing me a lot of problems.

**Comment by Bakkestaffen** [comment]
Ok, this is really weird. It's working now, but only when I click on the site through other user's hyperlinks and then using the site from that point forward. When I enter the address on my own, it's still blank.

Also, there are some smaller games that don't have it implemented. Shall I link them, or is this something you can implement yourself?

**Comment by ClassicSpeed** [comment]
I'll try to look around for the hyperlink or something, but if the game doesn't have info on HLTB, it won't work and it not something that I can fix on my end.

**Comment by Bakkestaffen** [comment]
No, almost all the ones I could find does. For example: https://howlongtobeat.com/game/42129 and nothing https://www.backloggd.com/games/okaeri-chibi-robo-happy-richie-oosouji/

Same here: https://howlongtobeat.com/game/27879

https://www.backloggd.com/games/boku-no-natsuyasumi-2-umi-no-bouken-hen/

**Comment by ClassicSpeed** [comment]
Sorry for de delay I had a busy week. I have free time tomorrow and see if I can solve both issues. Thanks for the report and for the examples!

**Comment by Gryyre** [comment]
I was having a similar problem on Firefox, where the time badges weren't showing up at all, but I think I figured out why:
On backloggd.com, the extension says "Can't read and change data on this site", but on **www**.backloggd.com, it works fine and the time badges show up and have the proper data. I don't have any experience with developing extensions but I would assume removing the www part of the URL would fix my issue?

**Comment by Bakkestaffen** [comment]
> I was having a similar problem on Firefox, where the time badges weren't showing up at all, but I think I figured out why: On backloggd.com, the extension says "Can't read and change data on this site", but on **www**.backloggd.com, it works fine and the time badges show up and have the proper data. I don't have any experience with developing extensions but I would assume removing the www part of the URL would fix my issue?

YES! That was the exact problem for me! It works when you add the www. Not without it. Also, there are tons of more examples on of games which lack the feature as mentioned above. Just look at any user lists made there of obscure games.

**Comment by ClassicSpeed** [comment]
Okay, I submitted the change without the www. to both Chrome and Firefox. The version 1.1 should be available in the next hours.

Now, regarding the games without times, the current problem is that the names are just difference. Chibi-Robo! Clean Sweep vs Okaeri! Chibi-Robo! Happy Richie Oosouji. According the igdb, the name being used by HLTB is a fan translation. But in the case of Boku no Natsuyasumi 2 none of the alternative names is the one used on HLTB.

So, the only solution that I could suggest if being hable to add the HLTB time manually. Not sure if that could be an acceptable solution.

**Comment by Bakkestaffen** [comment]
That would be a great solution, tbh. There are countless more games on the site which needs one. Like, there are even several Pokemon games which lacks one: https://www.backloggd.com/series/pokemon?page=1

Multiple games on this list, other than the two already mentioned: https://www.backloggd.com/u/wondershroom/list/backloggds-top-100-obscure-edition/ a few of them don't have HLTB pages, but most do.

There are even a few on the top 250 list which lacks one. Like Minecraft, likely due to it being renamed with 'Java Edition' as it's subtitle. https://www.backloggd.com/u/chump/list/backloggds-top-250?page=1

**Comment by ClassicSpeed** [comment]
Okay! Just to set some expectations about the solution I'm going to implement:
- It won't be anything pretty, it would probably have a question mark instead of the time if it didn't find one and just a simple input field to change the name that it uses when searching in HLTB, or probably just the HLTB id, since it's easier.
- It will work per user, as in, your manually added names won't be synced for me and vice versa.
- I'll try to developing the during next week, so expect the change the next weekend.

**Comment by Bakkestaffen** [comment]
There are also some errors. Like all Ratchet & Clank games have the same play time on them: https://backloggd.com/series/ratchet-clank/

The Walking Dead apparently only takes 30 minutes to complete? https://backloggd.com/games/the-walking-dead/

**Comment by Bakkestaffen** [comment]
Found another franchise with this problem: https://backloggd.com/series/mario-luigi/

**Comment by Bakkestaffen** [comment]
It hasn't worked for days now. You just get a - next to the games.

**Comment by ClassicSpeed** [comment]
The proxy for HLTB was fixed and it looks like this time won't break any time soon, so this was fixed!

**Comment by Bakkestaffen** [comment]
Really nice to see that problem being solved. But what about the other problems I've mentioned in this thread with games (sometimes entire franchises) being mislabeled and some games not being marked despite them being featured on hltb? Want me to make a new thread for those?

**Comment by Bakkestaffen** [comment]
Thanks, but I'll rather make a new one for these issues to avoid clutter. You can close this one.
