### ISSUE TITLE
Requests being blocked

### ISSUE THREAD

**Issue by Gryyre** [ClassicSpeed/backloggd-hltb#5]
The extension shows "-" on games it tries to fetch the info for. In the developer console, it shows these three errors for every game (example given with ZeroRanger):

`🚫 GET https://hltb-proxy.fly.dev/v1/query?title=ZeroRanger`

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://hltb-proxy.fly.dev/v1/query?title=ZeroRanger. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 500.`

`TypeError: NetworkError when attempting to fetch resource.`

I'm using Firefox 129.0.2.

**Comment by ClassicSpeed** [comment]
I'll try to fix it, thanks for the report!

**Comment by ClassicSpeed** [comment]
The proxy for HLTB was fixed and it looks like this time won't break any time soon, so this was fixed!
