### ISSUE TITLE
Times not appearing. Error in fetch function

### ISSUE THREAD

**Issue by VoladorSapo** [ClassicSpeed/backloggd-hltb#6]
In chrome, instead of the time, a line - now appears instead. I activated error collection and saw an error "Uncaught (in promise) TypeError: Failed to fetch" In the following function (the specific line is highlighted).

function fetchGameData(gameTitle) {
    return __awaiter(this, void 0, void 0, function* () {
        if (!(gameTitle in gameCache)) {
        ->    **const response = yield fetch(`https://hltb-proxy.fly.dev/v1/query?title=${gameTitle}`);**
            const data = yield response.json();
            if (!data || data.length === 0 || data[0].beatTime.main.avgSeconds <= 0) {
                gameCache[gameTitle] = null;
            }
            else {
                gameCache[gameTitle] = new HLTBGame(data[0]);
            }
        }
        return gameCache[gameTitle];
    });
}

time-badge.js:69 (función anónima)

It happens in both www.backloggd.com and backloggd.com.

My chrome version is 128.0.6613.114

**Comment by ClassicSpeed** [comment]
I'll try to fix it, thanks for the report!

**Comment by ClassicSpeed** [comment]
Something is broken on the proxy I use to fetch the HLTB data, it seems that HLTB doesn't like having an API. The proxy owner is probably going to fix it in the next couple of days but I'm afraid that if this keeps happening I should find a replacement for HLTB

**Comment by ClassicSpeed** [comment]
The proxy for HLTB was fixed and it looks like this time won't break any time soon, so this was fixed!
